# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Soy Simple OAuth
version: "1.2.0"
slug: soySimpleOAuth
description: Simple OAuth To Allow HomeAssistant Login Usage
url: "https://github.com/Soy-HA/HA-Addons/Soy_Kiosk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
