# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Soy_Kiosk"
version: "1.2.7"
slug: "Soy_Kiosk"
description: "Provides A Kiosk Mode"
url: "https://github.com/Soy-HA/HA-Addons/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386




