# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Soy_Kiosk"
version: "1.2.7"
slug: "Soy_Kiosk"
description: "Provides A Kiosk Mode"
url: "https://github.com/Soy-HA/HA-Addons/tree/main/Soy_Kiosk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  url: "http://homeassistant.local"
  client-key: ""
schema:
  url: "str?"
  client-key: "str?"
#image: "ghcr.io/home-assistant/{arch}-Soy-Kiosk"



