name: "Soy Kiosk"
description: "Displays A Dashboard without the fluff"
version: "1.1.0"
slug: "soy_kiosk"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080