name: "Soy Kiosk"
description: "Displays A Dashboard without the fluff"
version: "1.1.0"
slug: "soy_kiosk"
init: false
arch:
  - amd64
startup: services
ports:
  8080/tcp: 8080
map:
    - type: data
      read_only: False
options:
    home_assistant_location: "http://homeassistant.local"
    allow_outside_connections: False
    default_dashboard: "kiosk"
    kiosk_account_access_token: ""
schema:
    home_assistant_location: url
    allow_outside_connections: bool
    default_dashboard: "str?"
    kiosk_account_access_token: "str?"
    
#Add TO CONFIG   
#http:
#  use_x_frame_options: false