# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Soy Kiosk
version: "0.0.1"
slug: soyKiosk
description: Provides A Kiosk Mode
url: "https://github.com/Soy-HA/HA-Addons/Soy_Kiosk"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw

#image: "ghcr.io/home-assistant/{arch}-Soy-Kiosk"


